### ISSUE TITLE
[WEB][DRAFT][25 meters] Value the usage of Microservices

### ISSUE THREAD

**Issue by pymilone** [green-code-initiative/ecoCode-challenge#68]
# Architecture : Value the usage of Microservices
## Platform
| OS | OS version | Langage |
|---------------|--------------|------------|
| - | - | Javascript |
## Main caracteristics
| ID | Title | Category | Sub-category |
|----------|----------------------|-------------|----------------|
| {id} | {title} | {Category} | {SubCategory} |

## Severity / Remediation Cost
| Severity | Remediation Cost |
|------------|---------------------|
| High | Critical |

## Rule short description
Microservice or micro-frontend architecture is more sober than "classical" arhitecture since they allow lazy loading of javascript files.

## Text
Some architecture allow a lazy loading of javascript files thus saving bandwith and RAM 
Those architectures must be detected and valuated in terms of "green code score"

[TODO investigate whether lazy loading saves RAM or disk space]

## HTML
No HTML pattern yet

**Comment by jhertout** [comment]
Too generic to be declined as a rule. Keep in mind but can not be used like that. Should be closed in my point of view.

**Comment by utarwyn** [comment]
Hello! Even if this rule is very interesting, I agree that it will be difficult to implement it in an ecoCode plugin.

The Javascript ecosystem as of 2024 (with ESM module imports for example) also offers lazy-loading mechanisms. Also, I'm not convinced that using a framework is "greener" than using modules for a very basic site - because the framework does carry a certain weight -.

On the other hand, I fully agree that lazy-loading is essential for a growing site, to load a part of the site only when accessed by the user. But as explained in the description, I don't get the impression that this is the main point of the ticket. It's very difficult to predict the right or wrong use of lazy-loading with a static analysis of the source code, but I'd be interested in a solution if you have one.

These different arguments lead me to say that this ticket could be closed.
