### ISSUE TITLE
[WEB][DRAFT][25 meters] Value usage of Webcomponents instead of JS Frameworks

### ISSUE THREAD

**Issue by pymilone** [green-code-initiative/ecoCode-challenge#75]
# Architecture: Value usage of WebComponents

## Platform
| OS | OS version | Langage |
|---------------|--------------|------------|
| -  | - | JS |

## Main caracteristics
| ID | Title | Category | Sub-category |
|----------|----------------------|-------------|----------------|
| {id} | {title} | {Category} | {SubCategory} |

## Severity / Remediation Cost
| Severity | Remediation Cost |
|------------|---------------------|
| Low | High |

## Rule short description
Since WebComponents are natively included in browsers, they are more lightweight than javascript frameworks.

## Text
Using native components is more lightweight than using libraries.

## Implementation principle
Detect wether WebComponents or javascript frameworks are used and take it into account in a global score.

**Comment by jhertout** [comment]
Too generic in my point of view to be implemented as a rule. The idea is not bad but too much work is required at this point to create implementable rules in ecoCode. For this kind of rules, we need to be more precise.

**Comment by utarwyn** [comment]
Hello! In principle, I agree with the ticket statement: using a component developed as a native web component is less cumbersome than a framework component, because it doesn't embed any additional JavaScript to run the framework engine. But that's just theory. In my opinion, this rule poses the following problems and requires action:

- A single web component will indeed be lighter, but for a large site with hundreds/thousands of components? maybe this rule would no longer be so true? from how many? hard to predict.
- How to implement this rule in the ecoCode plugin? there are lots of ways to add a component and the risk of false positives is quite high in my opinion
- Does that mean you can't use Web frameworks? I think that's far too restrictive, don't you?

With all these questions raised, I'm in favor of closing the ticket for the time being, pending further investigations and more precise ideas.
